version: '3'
services:
  springboot-container:
    container_name: springboot-container
    build: .
    ports:
      - 8081:8080
    environment:
    - USER_DB_URL=jdbc:mariadb://mariadb:3306/springbootdb

networks:
  default:
    external:
      name: my-network
