version: '3'

services:
  db:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - 3306:3306

networks:
  default:
    external:
      name: my-network
